import { category, Product, Review } from './types';
export const categories: Record<string, category> = {
	Snacks: {
		icon: 'gi/GiChipsBag',
		to: '/products/snacks',
		products: [
			{ name: 'Popcorn', to: '/products/snacks/popcorn' },
			{ name: 'Crackers', to: '/products/snacks/crackers' },
			{ name: 'Chips', to: '/products/snacks/chips' },
		],
	},
	Sweets: {
		icon: 'lu/LuCandy',
		to: '/products/sweets',
		products: [
			{ name: 'Candies', to: '/products/sweets/candies' },
			{ name: 'Gum', to: '/products/sweets/gum' },
			{ name: 'Cookies', to: '/products/sweets/cookies' },
		],
	},
	Drinks: {
		icon: 'ri/RiDrinks2Fill',
		to: '/products/drinks',
		products: [
			{ name: 'Juices', to: '/products/drinks/juices' },
			{ name: 'Milkshakes', to: '/products/drinks/milkshakes' },
		],
	},
};

export const products: Product[] = [
	{
		category: 'snacks',
		type: 'chips',
		price: 5.0,
		oldPrice: 8.0,
		image: 'https://i.ibb.co/vx7mN8rj/premium-blchips.png',
		imageAlt: 'Premium BL Chips Image',
		label: 'Premium BL Chips',
		rating: 4.3,
		ratingCount: 12,
		pageLink: '/products/snacks/chips/premium-bl-chips',
		id: '0004',
		description: 'Premium quality crispy chips',
		isBestseller: true,
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 8.75,
		image: 'https://i.ibb.co/DfQwbBGS/catrios-chips.png',
		imageAlt: 'Catrios Chips Image',
		label: 'Catrios Chips',
		rating: 4.5,
		ratingCount: 14,
		pageLink: '/products/snacks/chips/catrios-chips',
		id: '0001',
		description: 'Spanish salty chips',
		isBestseller: false,
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.5,
		image: 'https://i.ibb.co/7F6Y020/chvatjners-chips.png',
		imageAlt: 'Chvatjners Chips Image',
		label: 'Chvatjners Chips',
		rating: 4.75,
		ratingCount: 9,
		pageLink: '/products/snacks/chips/chvatjners-chips',
		id: '0002',
		isBestseller: false,
		description: 'Swedish pepper chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 2.5,
		image: 'https://i.ibb.co/K1XjKRY/park-of-chips.png',
		imageAlt: 'Park Of Chips Image',
		label: 'Park Of Chips',
		rating: 4.25,
		ratingCount: 19,
		pageLink: '/products/snacks/chips/park-of-chips',
		id: '0003',
		isBestseller: false,
		description: 'American corn chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.5,
		image: 'https://i.ibb.co/FqYDcDpX/broghiss-chips.png',
		imageAlt: 'Broghiss Chips Image',
		label: 'Broghiss Chips',
		rating: 4.6,
		ratingCount: 11,
		pageLink: '/products/snacks/chips/broghiss-chips',
		id: '0005',
		isBestseller: false,
		description: 'Crispy potato snack',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 6.0,
		oldPrice: 9.0,
		image: 'https://i.ibb.co/4RCNrfQD/prajds-chips.png',
		imageAlt: 'Prajds Chips Image',
		label: 'Prajds Chips',
		rating: 4.8,
		ratingCount: 16,
		pageLink: '/products/snacks/chips/prajds-chips',
		id: '0006',
		isBestseller: false,
		description: 'Seasoned and crunchy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 5.5,
		image: 'https://i.ibb.co/39v3HdJ6/balfirge-bhips.png',
		imageAlt: 'Balfirge Bhips Image',
		label: 'Balfirge Bhips',
		rating: 4.7,
		ratingCount: 10,
		pageLink: '/products/snacks/chips/balfirge-bhips',
		id: '0007',
		isBestseller: false,
		description: 'Flavorful crispy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.75,
		image: 'https://i.ibb.co/JRw9wz6Y/rralky-chppss.png',
		imageAlt: 'Rralky Chips Image',
		label: 'Rralky Chips',
		rating: 4.4,
		ratingCount: 13,
		pageLink: '/products/snacks/chips/rralky-chppss',
		id: '0008',
		isBestseller: false,
		description: 'Spicy crunchy chips',
	},
	{
		isBestseller: false,
		category: 'snacks',
		type: 'chips',
		price: 2.25,
		oldPrice: 4,
		image: 'https://i.ibb.co/27gQNccK/bhip-chps.png',
		imageAlt: 'Bhip Chips Image',
		label: 'Bhip Chips',
		rating: 4.2,
		ratingCount: 15,
		pageLink: '/products/snacks/chips/bhip-chps',
		id: '0009',
		description: 'Classic salted chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.0,
		image: 'https://i.ibb.co/Lh288gR5/bhide-chips.png',
		imageAlt: 'Bhide Chips Image',
		isBestseller: false,
		label: 'Bhide Chips',
		rating: 4.1,
		ratingCount: 18,
		pageLink: '/products/snacks/chips/bhide-chips',
		id: '0010',
		description: 'Crispy potato chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.0,
		image: 'https://i.ibb.co/0jWrg5G0/rasun-chips.png',
		imageAlt: 'Rasun Chips Image',
		label: 'Rasun Chips',
		rating: 4.5,
		isBestseller: false,
		ratingCount: 14,
		pageLink: '/products/snacks/chips/rasun-chips',
		id: '0011',
		description: 'Savory crunchy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.25,
		image: 'https://i.ibb.co/Zzgpxcsn/drolh-chips.png',
		imageAlt: 'Drolh Chips Image',
		label: 'Drolh Chips',
		rating: 4.6,
		ratingCount: 12,
		pageLink: '/products/snacks/chips/drolh-chips',
		isBestseller: false,
		id: '0012',
		description: 'Tasty potato chips',
	},
	{
		category: 'snacks',
		isBestseller: false,
		type: 'chips',
		price: 5.0,
		image: 'https://i.ibb.co/wrRBwqHf/rijg-chips.png',
		imageAlt: 'Rijg Chips Image',
		label: 'Rijg Chips',
		rating: 4.8,
		ratingCount: 17,
		pageLink: '/products/snacks/chips/rijg-chips',
		id: '0013',
		description: 'Delicious crispy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 2.75,
		image: 'https://i.ibb.co/mV7bqgjr/chispy-chips.png',
		imageAlt: 'Chispy Chips Image',
		label: 'Chispy Chips',
		rating: 4.4,
		ratingCount: 20,
		pageLink: '/products/snacks/chips/chispy-chips',
		id: '0014',
		isBestseller: false,
		description: 'Crispy and tasty chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.5,
		image: 'https://i.ibb.co/3mXSqQ1q/chp-chapys-chips.png',
		imageAlt: 'Chp Chapys Chips Image',
		label: 'Chp Chapys Chips',
		rating: 4.3,
		isBestseller: false,
		ratingCount: 8,
		pageLink: '/products/snacks/chips/chp-chapys-chips',
		id: '0015',
		description: 'Crunchy flavorful chips',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		oldPrice: 4.0,
		isBestseller: true,
		image: 'https://i.ibb.co/N2L0kTcw/poppi-con-popcorn.png',
		imageAlt: 'Poppi Con Popcorn Image',
		label: 'Poppi Con Popcorn',
		rating: 4.5,
		ratingCount: 12,
		pageLink: '/products/snacks/popcorn/poppi-con-popcorn',
		id: '0016',
		description: 'Delicious caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/5zBQmNb/propin-popcorn.png',
		imageAlt: 'Propin Popcorn Image',
		label: 'Propin Popcorn',
		rating: 4.7,
		ratingCount: 25,
		isBestseller: false,
		pageLink: '/products/snacks/popcorn/propin-popcorn',
		id: '0017',
		description: 'Sweet and salty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.25,
		image: 'https://i.ibb.co/ZpxqKL8w/popcovr-popcorn.png',
		imageAlt: 'Popcovr Popcorn Image',
		label: 'Popcovr Popcorn',
		rating: 4.3,
		ratingCount: 30,
		pageLink: '/products/snacks/popcorn/popcovr-popcorn',
		id: '0018',
		description: 'Flavor-packed buttery popcorn',
		isBestseller: false,
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.95,
		image: 'https://i.ibb.co/WNK87ys6/proc-7oin-popcorn.png',
		imageAlt: 'Proc 7oin Popcorn Image',
		label: 'Proc 7oin Popcorn',
		rating: 4.1,
		ratingCount: 18,
		pageLink: '/products/snacks/popcorn/proc-7oin-popcorn',
		isBestseller: false,
		id: '0019',
		description: 'Crispy and light popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.75,
		image: 'https://i.ibb.co/Fb58BzDg/popp-cocon-popcorn.png',
		imageAlt: 'Popp Cocon Popcorn Image',
		isBestseller: false,
		label: 'Popp Cocon Popcorn',
		rating: 4.6,
		ratingCount: 40,
		pageLink: '/products/snacks/popcorn/popp-cocon-popcorn',
		id: '0020',
		description: 'Coconut flavored popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.2,
		oldPrice: 3.8,
		image: 'https://i.ibb.co/7NVSmJ1H/pecow-popcorn.png',
		imageAlt: 'Pecow Popcorn Image',
		isBestseller: false,
		label: 'Pecow Popcorn',
		rating: 4.4,
		ratingCount: 15,
		pageLink: '/products/snacks/popcorn/pecow-popcorn',
		id: '0021',
		description: 'Cheese burst popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/S7tf2KMc/piopn-pocop-popcorn.png',
		imageAlt: 'Piopn Pocop Popcorn Image',
		label: 'Piopn Pocop Popcorn',
		isBestseller: false,
		rating: 4.2,
		ratingCount: 22,
		pageLink: '/products/snacks/popcorn/piopn-pocop-popcorn',
		id: '0022',
		description: 'Spicy zesty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.85,
		image: 'https://i.ibb.co/Gqcs54k/bcon-popcorn.png',
		imageAlt: 'Bcon Popcorn Image',
		label: 'Bcon Popcorn',
		rating: 4.0,
		ratingCount: 10,
		pageLink: '/products/snacks/popcorn/bcon-popcorn',
		isBestseller: false,
		id: '0023',
		description: 'Bacon-flavored popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		image: 'https://i.ibb.co/XncGfpH/pocin-popcorn.png',
		imageAlt: 'Pocin Popcorn Image',
		label: 'Pocin Popcorn',
		isBestseller: false,
		rating: 4.7,
		ratingCount: 35,
		pageLink: '/products/snacks/popcorn/pocin-popcorn',
		id: '0024',
		description: 'Rich buttery popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/x8KL7WMV/prononn-sppp-bopen-popcorn.png',
		imageAlt: 'Prononn Sppp Bopen Popcorn Image',
		label: 'Prononn Popcorn',
		rating: 4.3,
		isBestseller: false,
		ratingCount: 16,
		pageLink: '/products/snacks/popcorn/prononn-sppp-bopen-popcorn',
		id: '0025',
		description: 'Crispy caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.2,
		image: 'https://i.ibb.co/WpfHDcQS/pop-con-popcorn.png',
		imageAlt: 'Pop Con Popcorn Image',
		label: 'Pop Con Popcorn',
		isBestseller: false,
		rating: 4.4,
		ratingCount: 50,
		pageLink: '/products/snacks/popcorn/pop-con-popcorn',
		id: '0026',
		description: 'Sweet and crunchy popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.4,
		oldPrice: 3.8,
		image: 'https://i.ibb.co/ptXJ9Qt/popp-rocin-popcorn.png',
		isBestseller: false,
		imageAlt: 'Popp Rocin Popcorn Image',
		label: 'Popp Rocin Popcorn',
		rating: 4.5,
		ratingCount: 27,
		pageLink: '/products/snacks/popcorn/popp-rocin-popcorn',
		id: '0027',
		description: 'Rich chocolate popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.95,
		image: 'https://i.ibb.co/b5Nf4k5k/popd-ocn-popcorn.png',
		imageAlt: 'Popd Ocn Popcorn Image',
		label: 'Popd Ocn Popcorn',
		isBestseller: false,
		rating: 4.0,
		ratingCount: 13,
		pageLink: '/products/snacks/popcorn/popd-ocn-popcorn',
		id: '0028',
		description: 'Light buttery popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		oldPrice: 4.0,
		image: 'https://i.ibb.co/27tBjTM8/pocpp-coon.png',
		imageAlt: 'Pocpp Coon Popcorn Image',
		label: 'Pocpp Coon Popcorn',
		isBestseller: false,
		rating: 4.5,
		ratingCount: 12,
		pageLink: '/products/snacks/popcorn/pocpp-coon-popcorn',
		id: '0029',
		description: 'Delicious caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/sdfnRSF1/prpoint-popcorn.png',
		imageAlt: 'Prpoint Popcorn Image',
		label: 'Prpoint Popcorn',
		rating: 4.7,
		ratingCount: 25,
		isBestseller: false,
		pageLink: '/products/snacks/popcorn/prpoint-popcorn',
		id: '0030',
		description: 'Sweet and salty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.25,
		image: 'https://i.ibb.co/gLgPn2pT/pocp-popcorn.png',
		imageAlt: 'Pocp Popcorn Image',
		label: 'Pocp Popcorn',
		isBestseller: false,
		rating: 4.3,
		ratingCount: 30,
		pageLink: '/products/snacks/popcorn/pocp-popcorn',
		id: '0031',
		description: 'Flavor-packed buttery popcorn',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.99,
		oldPrice: 4.49,
		isBestseller: true,
		image: 'https://i.ibb.co/wfy44CD/cookeps-cookies.png',
		imageAlt: 'Cookeps Cookies Image',
		label: 'Cookeps Cookies',
		rating: 4.5,
		ratingCount: 15,
		pageLink: '/products/sweets/cookies/cookeps-cookies',
		id: '0032',
		description: 'Delicious buttery cookies',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 2.99,
		image: 'https://i.ibb.co/Z69YsCST/chhes-cookie.png',
		imageAlt: 'Chhes Cookie Image',
		label: 'Chhes Cookie',
		isBestseller: false,
		rating: 4.2,
		ratingCount: 12,
		pageLink: '/products/sweets/cookies/chhes-cookie',
		id: '0033',
		description: 'Crunchy and tasty treat',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 4.25,
		image: 'https://i.ibb.co/wF0x25w7/chopies-cookies.png',
		imageAlt: 'Chopies Cookies Image',
		label: 'Chopies Cookies',
		isBestseller: false,
		rating: 4.7,
		ratingCount: 30,
		pageLink: '/products/sweets/cookies/chopies-cookies',
		id: '0034',
		description: 'Soft and chewy cookies',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.5,
		image: 'https://i.ibb.co/FLMsRzhB/chokes-cookies.png',
		isBestseller: false,
		imageAlt: 'Chokes Cookies Image',
		label: 'Chokes Cookies',
		rating: 4.3,
		ratingCount: 10,
		pageLink: '/products/sweets/cookies/chokes-cookies',
		id: '0035',
		description: 'Sweet and delicious flavor',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.0,
		image: 'https://i.ibb.co/67X70mWx/chopey-cookies.png',
		imageAlt: 'Chopey Cookies Image',
		label: 'Chopey Cookies',
		rating: 4.1,
		ratingCount: 25,
		pageLink: '/products/sweets/cookies/chopey-cookies',
		id: '0036',
		isBestseller: false,
		description: 'Crispy with a light texture',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.75,
		oldPrice: 4.0,
		image: 'https://i.ibb.co/B2N3BBfQ/chinp-cookies.png',
		imageAlt: 'Chinp Cookies Image',
		label: 'Chinp Cookies',
		isBestseller: false,
		rating: 4.6,
		ratingCount: 22,
		pageLink: '/products/sweets/cookies/chinp-cookies',
		id: '0037',
		description: 'Delightful crispy cookie bites',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 2.5,
		image: 'https://i.ibb.co/KpDX9JW8/chipy-cookies.png',
		imageAlt: 'Chipy Cookies Image',
		label: 'Chipy Cookies',
		rating: 4.0,
		ratingCount: 18,
		isBestseller: false,
		pageLink: '/products/sweets/cookies/chipy-cookies',
		id: '0038',
		description: 'Perfectly balanced flavor',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 4.0,
		image: 'https://i.ibb.co/60W1MWw1/chip-chop-choips-cookies.png',
		imageAlt: 'Chip Chop Choips Cookies Image',
		label: 'Chip Chop Choips Cookies',
		isBestseller: false,
		rating: 4.4,
		ratingCount: 35,
		pageLink: '/products/sweets/cookies/chip-chop-choips-cookies',
		id: '0039',
		description: 'Light and crispy chips cookies',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.25,
		image: 'https://i.ibb.co/TBGCyxk6/roc-choy-cookies.png',
		imageAlt: 'Roc Choy Cookies Image',
		label: 'Roc Choy Cookies',
		rating: 4.2,
		ratingCount: 14,
		pageLink: '/products/sweets/cookies/roc-choy-cookies',
		id: '0040',
		isBestseller: false,
		description: 'Crispy and delicious crunch',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.5,
		image: 'https://i.ibb.co/bMLDRBB4/chooke-cookies.png',
		imageAlt: 'Chooke Cookies Image',
		label: 'Chooke Cookies',
		rating: 4.6,
		ratingCount: 28,
		isBestseller: false,
		pageLink: '/products/sweets/cookies/chooke-cookies',
		id: '0041',
		description: 'Crunchy cookie with unique flavor',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 4.1,
		image: 'https://i.ibb.co/PsXqTq9P/filoo-cookies.png',
		imageAlt: 'Filoo Cookies Image',
		label: 'Filoo Cookies',
		rating: 4.7,
		ratingCount: 40,
		isBestseller: false,
		pageLink: '/products/sweets/cookies/filoo-cookies',
		id: '0042',
		description: 'Soft and chocolatey goodness',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.25,
		oldPrice: 3.75,
		isBestseller: true,
		image: 'https://i.ibb.co/ffd5ffw/chopps-cookeis.png',
		imageAlt: 'Chopps Cookies Image',
		label: 'Chopps Cookies',
		rating: 4.3,
		ratingCount: 50,
		pageLink: '/products/sweets/cookies/chopps-cookeis',
		id: '0043',
		description: 'Crispy, sweet, and addictive',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 2.75,
		oldPrice: 4.0,
		isBestseller: true,
		image: 'https://i.ibb.co/d0LD1T0K/chiolas-cookies.png',
		imageAlt: 'Chiolas Cookies Image',
		label: 'Chiolas Cookies',
		rating: 4.4,
		ratingCount: 45,
		pageLink: '/products/sweets/cookies/chiolas-cookies',
		id: '0044',
		description: 'Buttery and soft texture',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.0,
		image: 'https://i.ibb.co/fdbWkcNj/rhopys-cookies.png',
		imageAlt: 'Rhopys Cookies Image',
		label: 'Rhopys Cookies',
		rating: 4.1,
		ratingCount: 16,
		pageLink: '/products/sweets/cookies/rhopys-cookies',
		isBestseller: false,
		id: '0045',
		description: 'Perfect balance of sweetness',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 4.25,
		image: 'https://i.ibb.co/Y4TgnfFn/blues-chokes-cookies.png',
		imageAlt: 'Blues Chokes Cookies Image',
		label: 'Blues Chokes Cookies',
		rating: 4.5,
		ratingCount: 30,
		isBestseller: false,
		pageLink: '/products/sweets/cookies/blues-chokes-cookies',
		id: '0046',
		description: 'Rich and crispy delight',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 2.8,
		image: 'https://i.ibb.co/bjXpSGcL/chooters-cookies.png',
		imageAlt: 'Chooters Cookies Image',
		label: 'Chooters Cookies',
		rating: 4.3,
		isBestseller: false,
		ratingCount: 24,
		pageLink: '/products/sweets/cookies/chooters-cookies',
		id: '0047',
		description: 'Light and crispy cookies',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.6,
		image: 'https://i.ibb.co/qLqy2F8n/chmoers-cookies.png',
		imageAlt: 'Chmoers Cookies Image',
		label: 'Chmoers Cookies',
		rating: 4.4,
		isBestseller: false,
		ratingCount: 33,
		pageLink: '/products/sweets/cookies/chmoers-cookies',
		id: '0048',
		description: 'Crunchy and creamy goodness',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 3.0,
		image: 'https://i.ibb.co/sMGBbWm/ceo-bill-cookies.png',
		imageAlt: 'Ceo Bill Cookies Image',
		label: 'Ceo Bill Cookies',
		rating: 4.0,
		isBestseller: false,
		ratingCount: 22,
		pageLink: '/products/sweets/cookies/ceo-bill-cookies',
		id: '0049',
		description: 'Smooth and sweet cookie bite',
	},
	{
		category: 'sweets',
		type: 'cookies',
		price: 4.0,
		image: 'https://i.ibb.co/v6DRsXRc/chokie-cookies.png',
		imageAlt: 'Chokie Cookies Image',
		label: 'Chokie Cookies',
		rating: 4.6,
		ratingCount: 40,
		isBestseller: false,
		pageLink: '/products/sweets/cookies/chokie-cookies',
		id: '0050',
		description: 'Crunchy and rich in flavor',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 2.8,
		image: 'https://i.ibb.co/21XjD2nV/camiom-crackers.png',
		imageAlt: 'Camiom Crackers Image',
		label: 'Camiom Crackers',
		rating: 4.3,
		isBestseller: false,
		ratingCount: 18,
		pageLink: '/products/snacks/crackers/camiom-crackers',
		id: '0051',
		description: 'Crispy and flavorful snack',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 3.0,
		image: 'https://i.ibb.co/p6KZjWC7/caaker-crackers.png',
		imageAlt: 'Caaker Crackers Image',
		label: 'Caaker Crackers',
		rating: 4.2,
		ratingCount: 15,
		isBestseller: false,
		pageLink: '/products/snacks/crackers/caaker-crackers',
		id: '0052',
		description: 'Deliciously crunchy crackers',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 2.5,
		oldPrice: 3.75,
		isBestseller: true,
		image: 'https://i.ibb.co/HD5yBFNV/crahior-crackers.png',
		imageAlt: 'Crahiior Crackers Image',
		label: 'Crahiior Crackers',
		rating: 4.1,
		ratingCount: 22,
		pageLink: '/products/snacks/crackers/crahior-crackers',
		id: '0053',
		description: 'Tasty crackers with a bite',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 3.5,
		image: 'https://i.ibb.co/jZPdM5C5/caanon-crackers.png',
		imageAlt: 'Caanon Crackers Image',
		label: 'Caanon Crackers',
		rating: 4.4,
		ratingCount: 20,
		pageLink: '/products/snacks/crackers/caanon-crackers',
		isBestseller: false,
		id: '0054',
		description: 'Light and crunchy cracker snacks',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 2.9,
		image: 'https://i.ibb.co/m5RBgLVK/suan-car-cous-crackers.png',
		imageAlt: 'Suan Car Cous Crackers Image',
		label: 'Suan Car Cous Crackers',
		rating: 4.0,
		ratingCount: 17,
		isBestseller: false,
		pageLink: '/products/snacks/crackers/suan-car-cous-crackers',
		id: '0055',
		description: 'Crisp and delightful flavor',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 3.1,
		image: 'https://i.ibb.co/5x6MpyPP/bugen-crackers.png',
		imageAlt: 'Bugen Crackers Image',
		label: 'Bugen Crackers',
		rating: 4.5,
		isBestseller: false,
		ratingCount: 30,
		pageLink: '/products/snacks/crackers/bugen-crackers',
		id: '0056',
		description: 'Savory crackers for all tastes',
	},
	{
		category: 'snacks',
		type: 'crackers',
		price: 3.25,
		image: 'https://i.ibb.co/rR9Djng1/canckon-crackers.png',
		imageAlt: 'Canckon Crackers Image',
		label: 'Canckon Crackers',
		rating: 4.3,
		ratingCount: 25,
		pageLink: '/products/snacks/crackers/canckon-crackers',
		isBestseller: false,
		id: '0057',
		description: 'Perfectly crispy and savory',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 2.5,
		oldPrice: 4.0,
		isBestseller: true,
		image: 'https://i.ibb.co/sx5ZCMs/couj-candies.png',
		imageAlt: 'Couj Candies Image',
		label: 'Couj Candies',
		rating: 4.2,
		ratingCount: 18,
		pageLink: '/products/sweets/candies/couj-candies',
		id: '0058',
		description: 'Sweet and fruity candies',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 3.0,
		image: 'https://i.ibb.co/V0JThvFq/bildy-coy-candies.png',
		imageAlt: 'Bildy Coy Candies Image',
		label: 'Bildy Coy Candies',
		rating: 4.4,
		isBestseller: false,
		ratingCount: 25,
		pageLink: '/products/sweets/candies/bildy-coy-candies',
		id: '0059',
		description: 'Delicious chewy candies',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 2.8,
		image: 'https://i.ibb.co/BHKdwXZJ/candy-candies.png',
		imageAlt: 'Candy Candies Image',
		label: 'Candy Candies',
		rating: 4.0,
		ratingCount: 20,
		isBestseller: false,
		pageLink: '/products/sweets/candies/candy-candies',
		id: '0060',
		description: 'A perfect sweet treat',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 3.25,
		image: 'https://i.ibb.co/CK2VTnM0/cameon-candies.png',
		imageAlt: 'Cameon Candies Image',
		label: 'Cameon Candies',
		isBestseller: false,
		rating: 4.6,
		ratingCount: 30,
		pageLink: '/products/sweets/candies/cameon-candies',
		id: '0061',
		description: 'Fruity and tangy flavor',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 3.5,
		image: 'https://i.ibb.co/1f8J4Pny/camoon-cholce-candies.png',
		imageAlt: 'Camoon Cholce Candies Image',
		label: 'Camoon Cholce Candies',
		rating: 4.3,
		ratingCount: 35,
		isBestseller: false,
		pageLink: '/products/sweets/candies/camoon-cholce-candies',
		id: '0062',
		description: 'Chocolate and caramel candies',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 2.9,
		image: 'https://i.ibb.co/JWRW5G0j/chorn-candies.png',
		imageAlt: 'Chorn Candies Image',
		label: 'Chorn Candies',
		rating: 4.1,
		ratingCount: 22,
		pageLink: '/products/sweets/candies/chorn-candies',
		id: '0063',
		description: 'Chewy and flavorful candies',
		isBestseller: false,
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 3.0,
		image: 'https://i.ibb.co/qLjj5ddd/mima-candies.png',
		imageAlt: 'Mima Candies Image',
		label: 'Mima Candies',
		rating: 4.5,
		ratingCount: 40,
		pageLink: '/products/sweets/candies/mima-candies',
		id: '0064',
		description: 'Creamy and soft candies',
		isBestseller: false,
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 4.2,
		oldPrice: 6.0,
		isBestseller: true,
		image: 'https://i.ibb.co/GQgRLWp7/moimon-candies.png',
		imageAlt: 'Moimon Candies Image',
		label: 'Moimon Candies',
		rating: 4.6,
		ratingCount: 50,
		pageLink: '/products/sweets/candies/moimon-candies',
		id: '0065',
		description: 'Rich in flavor and texture',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 2.7,
		image: 'https://i.ibb.co/604RNNMN/monon-candies.png',
		imageAlt: 'Monon Candies Image',
		label: 'Monon Candies',
		rating: 4.3,
		ratingCount: 28,
		pageLink: '/products/sweets/candies/monon-candies',
		id: '0066',
		isBestseller: false,
		description: 'Tasty and colorful candies',
	},
	{
		category: 'sweets',
		type: 'candies',
		price: 3.4,
		image: 'https://i.ibb.co/nsC3BVDY/mmk-mi-candies.png',
		imageAlt: 'MMK Mi Candies Image',
		label: 'MMK Mi Candies',
		rating: 4.2,
		ratingCount: 33,
		isBestseller: false,
		pageLink: '/products/sweets/candies/mmk-mi-candies',
		id: '0067',
		description: 'Delicious hard candy treats',
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 1.5,
		image: 'https://i.ibb.co/bg8WkMC6/camiem-gum.png',
		imageAlt: 'Camiem Gum Image',
		label: 'Camiem Gum',
		rating: 4.0,
		ratingCount: 18,
		pageLink: '/products/sweets/gum/camiem-gum',
		isBestseller: false,
		id: '0068',
		description: 'Refreshing mint gum',
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 1.8,
		image: 'https://i.ibb.co/5X89tyMn/undef-gum.png',
		imageAlt: 'Undef Gum Image',
		label: 'Undef Gum',
		rating: 4.2,
		ratingCount: 25,
		pageLink: '/products/sweets/gum/undef-gum',
		id: '0069',
		description: 'Sweet fruity gum',
		isBestseller: false,
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 1.6,
		image: 'https://i.ibb.co/Df94nbjq/cancon-gum.png',
		imageAlt: 'Cancon Gum Image',
		label: 'Cancon Gum',
		rating: 4.3,
		ratingCount: 22,
		isBestseller: false,
		pageLink: '/products/sweets/gum/cancon-gum',
		id: '0070',
		description: 'Long-lasting flavored gum',
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 1.75,
		image: 'https://i.ibb.co/svnp65dz/nario-gum.png',
		imageAlt: 'Nario Gum Image',
		label: 'Nario Gum',
		rating: 4.1,
		ratingCount: 20,
		pageLink: '/products/sweets/gum/nario-gum',
		isBestseller: false,
		id: '0071',
		description: 'Tangy and tasty gum',
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 6.0,
		oldPrice: 11.49,
		isBestseller: true,
		image: 'https://i.ibb.co/xqwcK0D1/pinkb-gum.png',
		imageAlt: 'Pinkb Gum Image',
		label: 'Pinkb Gum',
		rating: 4.9,
		ratingCount: 10,
		pageLink: '/products/sweets/gum/pinkb-gum',
		id: '0072',
		description: 'Chewy strawberry gum',
	},
	{
		category: 'sweets',
		type: 'gum',
		price: 3.9,
		image: 'https://i.ibb.co/Q7ss0Hvy/claron-gum.png',
		imageAlt: 'Claron Gum Image',
		label: 'Claron Gum',
		rating: 4.3,
		ratingCount: 28,
		isBestseller: false,
		pageLink: '/products/sweets/gum/claron-gum',
		id: '0073',
		description: 'Refreshing lemon gum',
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 4.0,
		image: 'https://i.ibb.co/tpVNJx5R/heecoley-milkshake.png',
		imageAlt: 'Heecoley Milkshake Image',
		label: 'Heecoley Milkshake',
		rating: 4.5,
		ratingCount: 40,
		pageLink: '/products/drinks/milkshakes/heecoley-milkshake',
		id: '0074',
		description: 'Creamy and rich milkshake',
		isBestseller: false,
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 4.2,
		image: 'https://i.ibb.co/Kp5gYyZ9/hecehers-milkshake.png',
		imageAlt: 'Hecehers Milkshake Image',
		label: 'Hecehers Milkshake',
		rating: 4.3,
		ratingCount: 32,
		pageLink: '/products/drinks/milkshakes/hecehers-milkshake',
		id: '0075',
		description: 'Smooth and delicious milkshake',
		isBestseller: false,
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 3.8,
		image: 'https://i.ibb.co/2BvtLLt/theaky-milkshake.png',
		imageAlt: 'Theaky Milkshake Image',
		label: 'Theaky Milkshake',
		rating: 4.6,
		ratingCount: 50,
		isBestseller: false,
		pageLink: '/products/drinks/milkshakes/theaky-milkshake',
		id: '0076',
		description: 'Perfectly blended creamy shake',
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 5.5,
		oldPrice: 9.4,
		image: 'https://i.ibb.co/cKpHy03B/mirmlly-milkshake.png',
		imageAlt: 'Mirmlly Milkshake Image',
		label: 'Mirmlly Milkshake',
		rating: 4.4,
		ratingCount: 28,
		isBestseller: false,
		pageLink: '/products/drinks/milkshakes/mirmlly-milkshake',
		id: '0077',
		description: 'Rich, creamy, and indulgent',
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 4.3,
		image: 'https://i.ibb.co/DP3nQ2RZ/heesley-milkshake.png',
		imageAlt: 'Heesley Milkshake Image',
		label: 'Heesley Milkshake',
		rating: 4.2,
		ratingCount: 35,
		pageLink: '/products/drinks/milkshakes/heesley-milkshake',
		isBestseller: false,
		id: '0078',
		description: 'Deliciously creamy milkshake',
	},
	{
		category: 'drinks',
		type: 'milkshakes',
		price: 4.1,
		image: 'https://i.ibb.co/WNCK9NzW/pheole-milkshake.png',
		imageAlt: 'Pheole Milkshake Image',
		label: 'Pheole Milkshake',
		rating: 4.3,
		ratingCount: 38,
		isBestseller: false,
		pageLink: '/products/drinks/milkshakes/pheole-milkshake',
		id: '0079',
		description: 'Creamy, smooth milkshake',
	},
	{
		category: 'drinks',
		type: 'juices',
		price: 2.5,
		image: 'https://i.ibb.co/3t3bzXt/caccn-juice.png',
		imageAlt: 'Caccn Juice Image',
		label: 'Caccn Juice',
		isBestseller: false,
		rating: 4.2,
		ratingCount: 30,
		pageLink: '/products/drinks/juices/caccn-juice',
		id: '0080',
		description: 'Refreshing citrus juice',
	},
	{
		category: 'drinks',
		type: 'juices',
		price: 2.8,
		image: 'https://i.ibb.co/GvbvfWbT/oceoj-juice.png',
		imageAlt: 'Oceoj Juice Image',
		label: 'Oceoj Juice',
		rating: 4.4,
		ratingCount: 25,
		isBestseller: false,
		pageLink: '/products/drinks/juices/oceoj-juice',
		id: '0081',
		description: 'Tropical fruity juice',
	},
	{
		category: 'drinks',
		type: 'juices',
		price: 2.6,
		image: 'https://i.ibb.co/tF7NxZY/roabery-juice.png',
		imageAlt: 'Roabery Juice Image',
		label: 'Roabery Juice',
		rating: 4.3,
		ratingCount: 28,
		isBestseller: false,
		pageLink: '/products/drinks/juices/roabery-juice',
		id: '0082',
		description: 'Delicious berry blend',
	},
	{
		category: 'drinks',
		type: 'juices',
		price: 3.0,
		image: 'https://i.ibb.co/LdDp1m54/ravemiv-juice.png',
		imageAlt: 'Ravemiv Juice Image',
		label: 'Ravemiv Juice',
		rating: 4.1,
		isBestseller: false,
		ratingCount: 22,
		pageLink: '/products/drinks/juices/ravemiv-juice',
		id: '0083',
		description: 'Mixed fruit juice',
	},
	{
		category: 'drinks',
		type: 'juices',
		price: 2.9,
		oldPrice: 4.3,
		isBestseller: true,
		image: 'https://i.ibb.co/BVx0MkJN/spiplee-juice.png',
		imageAlt: 'Spiplee Juice Image',
		label: 'Spiplee Juice',
		rating: 4.5,
		ratingCount: 35,
		pageLink: '/products/drinks/juices/spiplee-juice',
		id: '0084',
		description: 'Refreshing apple juice',
	},
	{
		category: 'secret-boxes',
		type: 'all',
		price: 10,
		oldPrice: 15,
		image: 'https://i.ibb.co/0ysCj4x0/secret-box-standard.png',
		imageAlt: 'Secret Boxes Image',
		label: 'Secret Box Standard',
		rating: 3.5,
		isBestseller: false,
		ratingCount: 35,
		pageLink: 'products/secret-boxes',
		id: '0085',
		description: 'Standard box with random snacks',
	},
	{
		category: 'secret-boxes',
		type: 'all',
		price: 25,
		oldPrice: 40,
		image: 'https://i.ibb.co/9HHVtYJB/secret-box-vip.png',
		imageAlt: 'Vip Secret Box Image',
		label: 'Secret Box Vip',
		rating: 4.25,
		ratingCount: 12,
		pageLink: 'products/secret-boxes/vip',
		isBestseller: false,
		id: '0086',
		description: 'Vip box with random snacks',
	},
	{
		category: 'secret-boxes',
		type: 'all',
		price: 40,
		oldPrice: 60,
		image: 'https://i.ibb.co/r21mgJth/secret-box-premium.png',
		imageAlt: 'Premium Secret Box Image',
		label: 'Secret Box Premium',
		rating: 4.9,
		ratingCount: 4,
		pageLink: 'products/secret-boxes/premium',
		isBestseller: false,
		id: '0087',
		description: 'Premium box with random snacks',
	},
];

export const reviews: Review[] = [
	{
		avatar: 'https://i.ibb.co/tMdp4zG2/Rita-James.png',
		name: 'Rite James',
		rating: 5,
		text: 'These chips are tasty! The flavor is just right, not too salty, and nice and crisp. Perfect snack!',
		productId: '0001',
		id: '0001',
	},
	{
		avatar: 'https://i.ibb.co/99RXpRtN/Jospeh-Warren.png',
		name: 'Jospeh Warren',
		rating: 5,
		text: 'Delicious chocolate cookies with a great balance of soft and crunchy. Perfect for sweet cravings!',
		productId: '0043',
		id: '0002',
	},
	{
		avatar: 'https://i.ibb.co/XxfKKcsN/Charles-Frost.png',
		name: 'Charles Frost',
		rating: 5,
		text: 'Refreshing apple juice with natural flavor, not too sweet—perfectly balanced and healthy!',
		productId: '0084',
		id: '0003',
	},
];
