import { category, Product } from './types';
export const categories: Record<string, category> = {
	Snacks: {
		icon: 'gi/GiChipsBag',
		to: '/products/snacks',
		products: [
			{ name: 'Popcorn', to: '/products/snacks/popcorn' },
			{ name: 'Crackers', to: '/products/snacks/crackers' },
			{ name: 'Chips', to: '/products/snacks/chips' },
			{ name: 'Croutons', to: '/products/snacks/croutons' },
			{ name: 'Nuts', to: '/products/snacks/nuts' },
		],
	},
	Sweets: {
		icon: 'lu/LuCandy',
		to: '/products/sweets',
		products: [
			{ name: 'Candies', to: '/products/sweets/candies' },
			{ name: 'Cakes', to: '/products/sweets/cakes' },
			{ name: 'Gums', to: '/products/sweets/gums' },
			{ name: 'Cookies', to: '/products/sweets/cookies' },
			{ name: 'Jelly', to: '/products/sweets/jelly' },
			{ name: 'Bars', to: '/products/sweets/bars' },
		],
	},
	Drinks: {
		icon: 'ri/RiDrinks2Fill',
		to: '/products/drinks',
		products: [
			{ name: 'Juices', to: '/products/drinks/juices' },
			{ name: 'Milkshakes', to: '/products/drinks/milkshakes' },
			{ name: 'Sport-drinks', to: '/products/drinks/sports-drinks' },
			{ name: 'Tea', to: '/products/drinks/tea' },
			{ name: 'Coffee', to: '/products/drinks/coffee' },
		],
	},
};

export const products: Product[] = [
	{
		category: 'snacks',
		type: 'chips',
		price: 5.0,
		oldPrice: 8.0,
		image: 'https://i.ibb.co/vx7mN8rj/premium-blchips.png',
		imageAlt: 'Premium BL Chips Image',
		label: 'Premium BL Chips',
		rating: 4.3,
		ratingCount: 12,
		pageLink: '/products/snacks/chips/premium-bl-chips',
		id: '0004',
		description: 'Premium quality crispy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 8.75,
		image: 'https://i.ibb.co/DfQwbBGS/catrios-chips.png',
		imageAlt: 'Catrios Chips Image',
		label: 'Catrios Chips',
		rating: 4.5,
		ratingCount: 14,
		pageLink: '/products/snacks/chips/catrios-chips',
		id: '0001',
		description: 'Spanish salty chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.5,
		image: 'https://i.ibb.co/7F6Y020/chvatjners-chips.png',
		imageAlt: 'Chvatjners Chips Image',
		label: 'Chvatjners Chips',
		rating: 4.75,
		ratingCount: 9,
		pageLink: '/products/snacks/chips/chvatjners-chips',
		id: '0002',
		description: 'Swedish pepper chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 2.5,
		image: 'https://i.ibb.co/K1XjKRY/park-of-chips.png',
		imageAlt: 'Park Of Chips Image',
		label: 'Park Of Chips',
		rating: 4.25,
		ratingCount: 19,
		pageLink: '/products/snacks/chips/park-of-chips',
		id: '0003',
		description: 'American corn chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.5,
		image: 'https://i.ibb.co/FqYDcDpX/broghiss-chips.png',
		imageAlt: 'Broghiss Chips Image',
		label: 'Broghiss Chips',
		rating: 4.6,
		ratingCount: 11,
		pageLink: '/products/snacks/chips/broghiss-chips',
		id: '0005',
		description: 'Crispy potato snack',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 6.0,
		oldPrice: 9.0,
		image: 'https://i.ibb.co/4RCNrfQD/prajds-chips.png',
		imageAlt: 'Prajds Chips Image',
		label: 'Prajds Chips',
		rating: 4.8,
		ratingCount: 16,
		pageLink: '/products/snacks/chips/prajds-chips',
		id: '0006',
		description: 'Seasoned and crunchy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 5.5,
		image: 'https://i.ibb.co/39v3HdJ6/balfirge-bhips.png',
		imageAlt: 'Balfirge Bhips Image',
		label: 'Balfirge Bhips',
		rating: 4.7,
		ratingCount: 10,
		pageLink: '/products/snacks/chips/balfirge-bhips',
		id: '0007',
		description: 'Flavorful crispy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.75,
		image: 'https://i.ibb.co/JRw9wz6Y/rralky-chppss.png',
		imageAlt: 'Rralky Chips Image',
		label: 'Rralky Chips',
		rating: 4.4,
		ratingCount: 13,
		pageLink: '/products/snacks/chips/rralky-chppss',
		id: '0008',
		description: 'Spicy crunchy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 2.25,
		oldPrice: 4,
		image: 'https://i.ibb.co/27gQNccK/bhip-chps.png',
		imageAlt: 'Bhip Chips Image',
		label: 'Bhip Chips',
		rating: 4.2,
		ratingCount: 15,
		pageLink: '/products/snacks/chips/bhip-chps',
		id: '0009',
		description: 'Classic salted chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.0,
		image: 'https://i.ibb.co/Lh288gR5/bhide-chips.png',
		imageAlt: 'Bhide Chips Image',
		label: 'Bhide Chips',
		rating: 4.1,
		ratingCount: 18,
		pageLink: '/products/snacks/chips/bhide-chips',
		id: '0010',
		description: 'Crispy potato chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.0,
		image: 'https://i.ibb.co/0jWrg5G0/rasun-chips.png',
		imageAlt: 'Rasun Chips Image',
		label: 'Rasun Chips',
		rating: 4.5,
		ratingCount: 14,
		pageLink: '/products/snacks/chips/rasun-chips',
		id: '0011',
		description: 'Savory crunchy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 4.25,
		image: 'https://i.ibb.co/Zzgpxcsn/drolh-chips.png',
		imageAlt: 'Drolh Chips Image',
		label: 'Drolh Chips',
		rating: 4.6,
		ratingCount: 12,
		pageLink: '/products/snacks/chips/drolh-chips',
		id: '0012',
		description: 'Tasty potato chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 5.0,
		image: 'https://i.ibb.co/wrRBwqHf/rijg-chips.png',
		imageAlt: 'Rijg Chips Image',
		label: 'Rijg Chips',
		rating: 4.8,
		ratingCount: 17,
		pageLink: '/products/snacks/chips/rijg-chips',
		id: '0013',
		description: 'Delicious crispy chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 2.75,
		image: 'https://i.ibb.co/mV7bqgjr/chispy-chips.png',
		imageAlt: 'Chispy Chips Image',
		label: 'Chispy Chips',
		rating: 4.4,
		ratingCount: 20,
		pageLink: '/products/snacks/chips/chispy-chips',
		id: '0014',
		description: 'Crispy and tasty chips',
	},
	{
		category: 'snacks',
		type: 'chips',
		price: 3.5,
		image: 'https://i.ibb.co/3mXSqQ1q/chp-chapys-chips.png',
		imageAlt: 'Chp Chapys Chips Image',
		label: 'Chp Chapys Chips',
		rating: 4.3,
		ratingCount: 8,
		pageLink: '/products/snacks/chips/chp-chapys-chips',
		id: '0015',
		description: 'Crunchy flavorful chips',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		oldPrice: 4.0,
		image: 'https://i.ibb.co/N2L0kTcw/poppi-con-popcorn.png',
		imageAlt: 'Poppi Con Popcorn Image',
		label: 'Poppi Con Popcorn',
		rating: 4.5,
		ratingCount: 12,
		pageLink: '/products/snacks/popcorn/poppi-con-popcorn',
		id: '0016',
		description: 'Delicious caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/5zBQmNb/propin-popcorn.png',
		imageAlt: 'Propin Popcorn Image',
		label: 'Propin Popcorn',
		rating: 4.7,
		ratingCount: 25,
		pageLink: '/products/snacks/popcorn/propin-popcorn',
		id: '0017',
		description: 'Sweet and salty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.25,
		image: 'https://i.ibb.co/ZpxqKL8w/popcovr-popcorn.png',
		imageAlt: 'Popcovr Popcorn Image',
		label: 'Popcovr Popcorn',
		rating: 4.3,
		ratingCount: 30,
		pageLink: '/products/snacks/popcorn/popcovr-popcorn',
		id: '0018',
		description: 'Flavor-packed buttery popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.95,
		image: 'https://i.ibb.co/WNK87ys6/proc-7oin-popcorn.png',
		imageAlt: 'Proc 7oin Popcorn Image',
		label: 'Proc 7oin Popcorn',
		rating: 4.1,
		ratingCount: 18,
		pageLink: '/products/snacks/popcorn/proc-7oin-popcorn',
		id: '0019',
		description: 'Crispy and light popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.75,
		image: 'https://i.ibb.co/Fb58BzDg/popp-cocon-popcorn.png',
		imageAlt: 'Popp Cocon Popcorn Image',
		label: 'Popp Cocon Popcorn',
		rating: 4.6,
		ratingCount: 40,
		pageLink: '/products/snacks/popcorn/popp-cocon-popcorn',
		id: '0020',
		description: 'Coconut flavored popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.2,
		oldPrice: 3.8,
		image: 'https://i.ibb.co/7NVSmJ1H/pecow-popcorn.png',
		imageAlt: 'Pecow Popcorn Image',
		label: 'Pecow Popcorn',
		rating: 4.4,
		ratingCount: 15,
		pageLink: '/products/snacks/popcorn/pecow-popcorn',
		id: '0021',
		description: 'Cheese burst popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/S7tf2KMc/piopn-pocop-popcorn.png',
		imageAlt: 'Piopn Pocop Popcorn Image',
		label: 'Piopn Pocop Popcorn',
		rating: 4.2,
		ratingCount: 22,
		pageLink: '/products/snacks/popcorn/piopn-pocop-popcorn',
		id: '0022',
		description: 'Spicy zesty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.85,
		image: 'https://i.ibb.co/Gqcs54k/bcon-popcorn.png',
		imageAlt: 'Bcon Popcorn Image',
		label: 'Bcon Popcorn',
		rating: 4.0,
		ratingCount: 10,
		pageLink: '/products/snacks/popcorn/bcon-popcorn',
		id: '0023',
		description: 'Bacon-flavored popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		image: 'https://i.ibb.co/XncGfpH/pocin-popcorn.png',
		imageAlt: 'Pocin Popcorn Image',
		label: 'Pocin Popcorn',
		rating: 4.7,
		ratingCount: 35,
		pageLink: '/products/snacks/popcorn/pocin-popcorn',
		id: '0024',
		description: 'Rich buttery popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/x8KL7WMV/prononn-sppp-bopen-popcorn.png',
		imageAlt: 'Prononn Sppp Bopen Popcorn Image',
		label: 'Prononn Popcorn',
		rating: 4.3,
		ratingCount: 16,
		pageLink: '/products/snacks/popcorn/prononn-sppp-bopen-popcorn',
		id: '0025',
		description: 'Crispy caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.2,
		image: 'https://i.ibb.co/WpfHDcQS/pop-con-popcorn.png',
		imageAlt: 'Pop Con Popcorn Image',
		label: 'Pop Con Popcorn',
		rating: 4.4,
		ratingCount: 50,
		pageLink: '/products/snacks/popcorn/pop-con-popcorn',
		id: '0026',
		description: 'Sweet and crunchy popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.4,
		oldPrice: 3.8,
		image: 'https://i.ibb.co/ptXJ9Qt/popp-rocin-popcorn.png',
		imageAlt: 'Popp Rocin Popcorn Image',
		label: 'Popp Rocin Popcorn',
		rating: 4.5,
		ratingCount: 27,
		pageLink: '/products/snacks/popcorn/popp-rocin-popcorn',
		id: '0027',
		description: 'Rich chocolate popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 2.95,
		image: 'https://i.ibb.co/b5Nf4k5k/popd-ocn-popcorn.png',
		imageAlt: 'Popd Ocn Popcorn Image',
		label: 'Popd Ocn Popcorn',
		rating: 4.0,
		ratingCount: 13,
		pageLink: '/products/snacks/popcorn/popd-ocn-popcorn',
		id: '0028',
		description: 'Light buttery popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.5,
		oldPrice: 4.0,
		image: 'https://i.ibb.co/27tBjTM8/pocpp-coon.png',
		imageAlt: 'Pocpp Coon Popcorn Image',
		label: 'Pocpp Coon Popcorn',
		rating: 4.5,
		ratingCount: 12,
		pageLink: '/products/snacks/popcorn/pocpp-coon-popcorn',
		id: '0029',
		description: 'Delicious caramel popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.0,
		image: 'https://i.ibb.co/sdfnRSF1/prpoint-popcorn.png',
		imageAlt: 'Prpoint Popcorn Image',
		label: 'Prpoint Popcorn',
		rating: 4.7,
		ratingCount: 25,
		pageLink: '/products/snacks/popcorn/prpoint-popcorn',
		id: '0030',
		description: 'Sweet and salty popcorn',
	},
	{
		category: 'snacks',
		type: 'popcorn',
		price: 3.25,
		image: 'https://i.ibb.co/gLgPn2pT/pocp-popcorn.png',
		imageAlt: 'Pocp Popcorn Image',
		label: 'Pocp Popcorn',
		rating: 4.3,
		ratingCount: 30,
		pageLink: '/products/snacks/popcorn/pocp-popcorn',
		id: '0031',
		description: 'Flavor-packed buttery popcorn',
	},
];
