name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to VDS and deploy
      uses: appleboy/ssh-action@v1
      with: 
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          cd /home/base/NadSnax
          git pull
          docker compose up -d --build